[project]
name = "pyqir-parser"
version = "0.7.0a1"
requires-python = ">= 3.7"

[project.optional-dependencies]
test = ["pytest ~= 7.1.3"]

[build-system]
requires = ["maturin ~= 0.13.6"]
build-backend = "maturin"
