name: pyqir-rust-$(BuildId)

trigger:
  branches:
    include:
    - main

parameters:
- name: matrix
  type: object
  default:
  - name: linux_x86_64
    poolName: 'Azure-Pipelines-DevTools-EO'
    imageName: 'ubuntu-22.04'
    os: linux
    tag: amd64
  - name: linux_aarch64
    poolName: 'Azure-Pipelines-DevTools-ARM64-EO'
    imageName: 'azurelinux-3.0-gen2-arm64'
    os: linux
    tag: arm64

# Parameters for building the Rust image
- name: ACR_SERVER
  displayName: Azure Container Registry server
  type: string
  default: 'qdkacr-cfgqhwddajdaebhg.azurecr.io'
- name: qdkLlvmTag
  displayName: Tag for the qdk-llvm base container image
  type: string
  default: 'latest'
- name: qdkRustTag
  displayName: Tag for the new qdk-rust container image
  type: string
  default: 'latest'

variables:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN_VERSION: "1.95"
  # If the user didn't specify a tag for the Rust image, use the build ID as the tag.
  ${{ if eq(parameters.qdkRustTag, 'latest') }}:
    finalRustTag: $(Build.BuildId)
  ${{ else }}:
    finalRustTag: ${{ parameters.qdkRustTag }}

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
  containers:
    - container: qdkLlvmImage
      image: ${{ parameters.ACR_SERVER }}/qdk-llvm:${{ parameters.qdkLlvmTag }}
      endpoint: qdkacr

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    settings:
      # To fetch the packages from the ADO feed, Azure blob access is needed.
      # See https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-build/cloudbuild/security/1espt-network-isolation
      networkIsolationPolicy: AzureStorage

    sdl:
      autobaseline:
        enableForGitHub: true
      sourceAnalysisPool:
        name: 'Azure-Pipelines-DevTools-EO'
        image: windows-2022
        os: windows
    stages:
    - stage: build
      displayName: Build
      jobs:
      - ${{ each target in parameters.matrix }}:
        - job: ${{ target.name }}
          pool:
            name: ${{ target.poolName }}
            image: ${{ target.imageName }}
            os: ${{ target.os }}
          timeoutInMinutes: 300
          templateContext:
            authenticatedContainerRegistries:
            - serviceConnection: qdkacr
          steps:
          - checkout: self

          - task: 1ES.BuildContainerImage@1
            inputs:
              path: $(Build.SourcesDirectory)/.ado/images/qdk-rust
              image: qdk-rust:$(finalRustTag)-${{ target.tag }}
              useBuildKit: true
              buildArguments: >
                --build-arg MSRUSTUP_FEED_URL=$(toolchainFeed)
                --build-arg RUST_TOOLCHAIN=ms-prod-$(RUST_TOOLCHAIN_VERSION)
                --secret id=msrustup_token,env=SYSTEM_ACCESSTOKEN
            env:
              SYSTEM_ACCESSTOKEN: $(System.AccessToken)
          
          - task: 1ES.PushContainerImage@1
            inputs:
              image: qdk-rust:$(finalRustTag)-${{ target.tag }}
              remoteImage: ${{ parameters.ACR_SERVER }}/qdk-rust:$(finalRustTag)-${{ target.tag }}
