on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: |
        Get-ChildItem (Join-Path "eng" "problem-matchers") `
          | ForEach-Object {
            Write-Host "Adding matcher $_...";
            Write-Host "::add-matcher::$_";
          }
      shell: pwsh

    - name: markdownlint-cli
      uses: nosborn/github-action-markdown-cli@v2.0.0
      with:
        files: .
        config_file: .markdownlint.yaml

    - name: Markdown link check
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-verbose-mode: yes
        config-file: utils/mlc_config.json
